// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlFqkXzLpOgv_Suis7ew2bco2gwb3EBMU',
    appId: '1:951208361900:web:4a4886f497e4e10e45c409',
    messagingSenderId: '951208361900',
    projectId: 'calso-8ca98',
    authDomain: 'calso-8ca98.firebaseapp.com',
    storageBucket: 'calso-8ca98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6NqqCQZpB1Vut3adLEA4SZorTybnvzEw',
    appId: '1:951208361900:android:cff5f26ce38aa3f945c409',
    messagingSenderId: '951208361900',
    projectId: 'calso-8ca98',
    storageBucket: 'calso-8ca98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFNOYpAlVEHey_1hmCPfnJn7tAH1t_Eo',
    appId: '1:951208361900:ios:ed1c7d24c23a099745c409',
    messagingSenderId: '951208361900',
    projectId: 'calso-8ca98',
    storageBucket: 'calso-8ca98.appspot.com',
    androidClientId: '951208361900-2tl7t71beeer8pontrf4vs5q4il6rk19.apps.googleusercontent.com',
    iosClientId: '951208361900-ftd3poo1mf3bhut5qdm84m61gf7h46fg.apps.googleusercontent.com',
    iosBundleId: 'com.calso',
  );
}
